# Generated by Django 5.2.17 on 2026-09-14 06:15

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('role', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('thumbnail', models.CharField(max_length=255)),
                ('primary_link_label', models.CharField(blank=True, max_length=100)),
                ('primary_link_url', models.URLField(blank=True)),
                ('secondary_link_label', models.CharField(blank=True, max_length=100)),
                ('secondary_link_url', models.URLField(blank=True)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('display_order', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
